### ISSUE TITLE
Unable to authenticate

### ISSUE THREAD

**Issue by sara-ferguson** [painebenjamin/vault-key#1]
Issue: 
- Unable to authenticate 

Environment: 
- google-chrome-stable-80.0.3987.106-1.x86_64
- Fedora 31

Description: 

I'm not sure what data I can provide, but the extension is unable to authenticate with my provided credentials. I had a friend try with the same credentials on his system and he was able to login as me via the extension. 

I am running on Fedora 31. I've disabled firewalld, set selinux to permissive, stopped my VPN, updated Chrome, and have removed/re-added the extension a few times. Screen shot of the error. 

![Screenshot from 2020-02-17 12-23-19](https://user-images.githubusercontent.com/51539427/74674913-5ad82580-5180-11ea-8c03-551293f459ee.png)

Checking the Network tab in the Chrome Devtools menu shows "CORS disallowed". I've attached the headers for this request in a separate file. I believe I've removed any personally identifying information. 

[git-hub-issue-vault-key-authenticate-headers.txt](https://github.com/painebenjamin/vault-key/files/4215294/git-hub-issue-vault-key-authenticate-headers.txt)

Please let me know if you need anything else, or if you have any questions or suggestions for me.

**Comment by painebenjamin** [comment]
Thanks a lot for the very detailed information, and thanks for going through all those debugging steps. You sent exactly what I need to see the issue - in your headers file, this is the origin:

**origin: chrome-extension://phlipcmdojgcpgkcloihjabigpkimjlh**

The 2K API is **not** meant to be accessed by anything other than the origins they've allowed. We don't know all of them, to be sure, but origin spoofing is an unfortunately necessary step - all requests coming from Vault Key have an origin of `borderlands.com`. That's why we add the `onBeforeSendHeaders` listener in `redeemer.js`, to inject the headers before the initial request begins. It looks like this listener is silently failing in your case.

I've personally used this extension on CentOS7, which is close enough in my mind to Fedora that it's unlikely to be OS-level difficulties, and I'm more inclined to say it's something to do with Chrome, but it looks like you've already tried a lot of steps. One thing you didn't mention, though - do you have an adblocker or other extension that might be stopping the extension from doing somewhat-nefarious-but-ultimately-necessary request hijacking? I haven't gotten uBlock origin to pop up on me, but there may be something else that flat-out refuses to send request with headers modified prior to transmission.

**Comment by mcswizzle** [comment]
I'm her friend who was able to authenticate for her, so here's my environment details for comparison. I wasn't running uBlock Origin at the time either, so she'll want to check that as well.

$ cat /etc/fedora-release 
Fedora release 30 (Thirty)

$ rpm -qi google-chrome-stable
Name        : google-chrome-stable
Version     : 78.0.3904.97
Architecture: x86_64

**Comment by sara-ferguson** [comment]
After some searching I found this Chrome flag:

`chrome://flags/#out-of-blink-cors`

After disabling and relaunching Chrome the extension works as expected! Going to go ahead and close this. Thanks for being so quick to respond! Love the extension, too. 

More info here: https://support.google.com/chrome/thread/11089651?hl=en

**Comment by painebenjamin** [comment]
Thanks a bunch for both links. Interesting that you experienced this, that thread calls out v76, but @mcswizzle and I are on v78 and didn't hit it, and you're on v80 and you did. I'll need to update my version and see if I can dig out the issue - technically it's not running in a content script _or_ a background page when you're looking at it on the options page (it should be operating as a run-of-the-mill intranet site with access the chrome internals), but it looks like it's treating it like one. I'll need to make the options page communicate with the background script, rather than just sharing a codebase with it.

**Comment by fragmi** [comment]
This now appears to be problematic in Chrome 84+ as the flags are no longer present. Cross Origin Request Sharing appears to be disabled/disallowed in chrome & rejected when authenticating against the 2k API. This is apparently to assist in the prevention of Spectre attacks etc.

**https://www.chromium.org/Home/chromium-security/extension-content-script-fetches**
